git rm --cached MDOF_Free_Response_Visc.m
git rm --cached MDOF_FRF_Point_Struc.m
git rm --cached MDOF_FRF_Point_Visc.m
git rm --cached MDOF_FRF_Visc.m
git rm --cached MDOF_Harmonic_Response_Visc.m
git rm --cached MDOF_IRF_Visc.m
git rm --cached quad_eig.m
git rm --cached SDOF_Free_Response_Visc.m
git rm --cached SDOF_FRF_Struc_mul_k.m
git rm --cached SDOF_FRF_Visc_mul_k.m
git rm --cached SDOF_Harmonic_Response_dot_Visc_mul_m.m
git rm --cached SDOF_Harmonic_Response_Visc_mul_m.m
git rm --cached SDOF_IRF_Visc_mul_m.m
git rm --cached SDOF_Vehicle_IRF.m
git rm --cached SDOF_Vehicle_Step_Response.m
